# -*-Perl-*-

## generate pdf not dvi
$pdf_mode = 1;

$aux_dir = ".auxdir";

$pdflatex = "pdflatex --shell-escape %O %S";

@generated_exts = (@generated_exts, 'loab', 'maf', 'los', 'mtc', 'idx', 
    'ilg', 'ind', 'mtc0', 'bbl', 'vrb', 'nav', 'run.xml', 'snm', 'ist', 
    'glg-abr', 'glo-abr', 'gls-abr');


add_cus_dep( 'acn', 'acr', 0, 'makeglossaries' );
add_cus_dep( 'glo', 'gls', 0, 'makeglossaries' );
add_cus_dep( 'ntn', 'not', 0, 'makeglossaries' );
$clean_ext .= " acr acn alg glo gls glg ist not ntn";

sub makeglossaries {
    my ($base_name, $path) = fileparse( $_[0] );
    pushd $path;
    my $return = system "makeglossaries", $base_name;
    popd;
    return $return;
}
